spring:
  config:
    import: optional:classpath:.env
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/booe
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
logging:
  level:
    org.hibernate.sql: debug

jwt:
  secret: ${JWT_SECRET}
  access_token_time : ${JWT_EXPIRATION_TIME}

api:
  public-data:
    base-url: https://apis.data.go.kr
    service-key: "mqbVrTExhyHssEcrak%2FHzS46eOEzi7aQK9%2B8kmpctOiotwNIyx6ItkxNOCBLT7NBR294hM29Jw0g5LAkIAYU%2Bw%3D%3D"
    timeout: 5000